name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help improve this project for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem does this feature solve? What need does it address?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative solutions or workarounds you've thought about
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Code Quality (linting, formatting, testing)
        - Documentation
        - Development Environment (setup, dependencies)
        - CI/CD (workflows, automation)
        - Data Processing
        - Python Tooling
        - R Tooling
        - Security
        - Performance
        - Project Structure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical for my workflow
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        Walk through a typical scenario where you'd use this feature.
        Example: "As a data scientist, I want to... so that I can..."
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved productivity
        - Better code quality
        - Easier onboarding
        - etc.
    validations:
      required: false

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        Technical suggestions, tools to use, examples from other projects, etc.
        (Optional - we're happy to figure this out!)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Links to similar features in other projects, mockups, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I would be willing to contribute to implementing this feature
          required: false
